In [6]:
import numpy as np

x = np.ones((3, 3))
x = np.zeros((8, 8), dtype = int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
import numpy as np

x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [18]:
import numpy as np

x = np.random.random((3, 3, 3))
print(x)

[[[0.04963806 0.08096873 0.15894421]
  [0.12951442 0.83068539 0.24463977]
  [0.3944124  0.9725699  0.76388681]]

 [[0.7470303  0.59223128 0.31798459]
  [0.46205138 0.18195743 0.3883022 ]
  [0.75403733 0.8185954  0.23431328]]

 [[0.24665857 0.44157724 0.32438549]
  [0.52397058 0.04034467 0.42956355]
  [0.85687488 0.12910946 0.34266673]]]


In [24]:
import numpy as np

a = int(input("Введите количество строк матрицы: "))
b = int(input("Введите количество столбцов матрицы: "))

x = np.ones((a, b))
x[1:-1, 1:-1] = 0
print(x)

Введите количество строк матрицы: 5
Введите количество столбцов матрицы: 6
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [35]:
import numpy as np

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
x = np.sort(arr * (-1))
print(x * (-1))

[8 7 6 5 4 3 2 1]


In [41]:
import numpy as np        #Доделать!

matrix = np.arange(25).reshape(5, 5)
print(matrix.shape)
print(matrix.size)

(5, 5)
25


In [44]:
import pandas as pd

a = pd.Series([8, 10, 12, 14])
b = pd.Series([1, 3, 5, 7])
print(sum((a - b)**2)**.5)

14.0


In [46]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

In [61]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe.head(3)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe.iloc[1:4]
dataframe[dataframe['capital'] == 0].head(10)

age         workclass  education_num         marital_status  \
1    50  Self-emp-not-inc             13     Married-civ-spouse   
2    38           Private              9               Divorced   
3    53           Private              7     Married-civ-spouse   
4    28           Private             13     Married-civ-spouse   
5    37           Private             14     Married-civ-spouse   
6    49           Private              5  Married-spouse-absent   
7    52  Self-emp-not-inc              9     Married-civ-spouse   
10   37           Private             10     Married-civ-spouse   
11   30         State-gov             13     Married-civ-spouse   
12   23           Private             13          Never-married   

           occupation   relationship   race  gender  hours_per_week  \
1     Exec-managerial        Husband  White    Male              13   
2   Handlers-cleaners  Not-in-family  White    Male              40   
3   Handlers-cleaners        Husband  Other    Male              40   
4      Prof-specialty           Wife  Other  Female              40   
5     Exec-managerial           Wife  White  Female              40   
6       Other-service  Not-in-family  Other  Female              16   
7     Exec-managerial        Husband  White    Male              45   
10    Exec-managerial        Husband  Other    Male              80   
11     Prof-specialty        Husband  Other    Male              40   
12       Adm-clerical      Own-child  White  Female              30   

   native_country  capital income_status  
1   United-States        0         <=50K  
2   United-States        0         <=50K  
3   United-States        0         <=50K  
4           Other        0         <=50K  
5   United-States        0         <=50K  
6           Other        0         <=50K  
7   United-States        0          >50K  
10  United-States        0          >50K  
11          Other        0          >50K  
12  United-States        0         <=50K

In [11]:
from sklearn import preprocessing
import numpy as np
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
scaler = MinMaxScaler()

dataframe['sepal_length_cm'] = scaler.fit_transform()
dataframe



TypeError: fit_transform() missing 1 required positional argument: 'X'